### PR TITLE
chore: #57 add card img test

### PR DESCRIPTION
**Pull request by greyGroot**
#57  add test for CardImg component

@daniel-norris

### CODE REVIEW

**Review by daniel-norris — CHANGES_REQUESTED** [review]
Hey @greyGroot, this is good work and the test currently pass - thanks. 

I'm going to ask for one more addition before we merge this please. Can you also test that a falsy value is passed if no `alt` prop is passed so we get a 100% coverage on the component? 

image

**Comment by greyGroot** [comment]
@daniel-norris done.

**Review by daniel-norris — APPROVED** [review]
Fair enough, I had something else originally in mind but that'll do! 😊

**Comment by daniel-norris** [comment]
Merged, thanks @greyGroot !

**Pull request merged**
