### PR TITLE
Add tests for Toggle to fix request #70

### PR DESCRIPTION
**Pull request by rdhaundiyal-indeed**
Added unit tests for Toggle component.

Notes: I could only add basic tests like rendering works and the rendered structure is as expected. If you have any specific cases in mind, please mention them here and I will add them as well. Thanks.

### CODE REVIEW

**Review by daniel-norris — CHANGES_REQUESTED** [review]
Hey @rdhaundiyal-indeed, firstly thanks for helping to contribute. 

This looks good so far but would you be able to add an additional test that also covers the on click behaviour of the toggle component please? 

image

At the moment, we're at 66% coverage and we want to try and hit 100% on all components. Let me know if you have any questions. 

There's a testing recipe for a toggle component using Jest in the React docs but the component is built differently. 

https://reactjs.org/docs/testing-recipes.html#events

**Comment by rdhaundiyal-indeed** [comment]
Done & verified coverage. However, the test needs to know internal details of the component because no external 'onClick' handler has been passed to it as props.

**Comment by rdhaundiyal-indeed** [comment]
Hi! I hope there's nothing pending on me.

**Comment by daniel-norris** [comment]
Hi @rdhaundiyal-indeed sorry for the delay in coming back to you. The past week has been crazy and it's been hard to find time in the evening to review PRs. 

I'm afraid someone has submitted a PR which has refactored the Toggle component - you can see PR #92. Your tests are now failing on this PR I'm afraid. It just looks like, on a quick review, that they're failing when trying to traverse the DOM. Only because the refactor has changed the structure a little bit.

**Pull request closed without merging**
