### PR TITLE
Setup jest-dom to extend test functionalities + Button tests

### PR DESCRIPTION
**Pull request by luizcieslak**
Hi! I was about to send you some unit tests but I notice that you didn't setup [jest-dom](https://github.com/testing-library/jest-dom) in your project.

I also write a test for `Button` using one of the custom matchers provided by them.

### CODE REVIEW

**Review by daniel-norris — CHANGES_REQUESTED** [review]
Hi @luizcieslak, firstly thanks for for contributing. There's one or two things we need to change before merging. 

The test currently fails the way it's setup. 

image

But it's only because the `import "@testing-library/jest-dom/extend-expect" ` should be imported into the `Button.test.js` file. Can you make this change and remove the `src/setupTests.js` file please. 

While you are changing the button tests; would you mind also testing for a situation where the prop accepts "large" as an argument and so the styling changes to `1.5rem`. That way, we'll have 100% coverage across the component and line 14 will be covered. 

image

Any questions, let me know. Thanks @luizcieslak 👍

**Comment by luizcieslak** [comment]
There was a bug in your Button, pushed a commit to fix it and add a test for when size is "large".

Regarding the setupTests, it is a [way](https://create-react-app.dev/docs/running-tests/#srcsetuptestsjs-1) to make it import and configure things in all of your test files at once. But I will remove it you prefer to not have it.

One thing is odd: The tests are passing it here, but I used a different setup from their [README](https://github.com/testing-library/jest-dom#usage)

instead of 

```js
import "@testing-library/jest-dom"
```

I used

```js
import "@testing-library/jest-dom/extend-expect"
```

could you check if with the first config, without the "/extend-expect" works in your machine?

**Review by daniel-norris — CHANGES_REQUESTED** [review]
There doesn't seem to be a change when changing the import to `import "@testing-library/jest-dom/extend-expect"`. 

Strangely, though... explicitly specifying the file location in the `package.json` file does enable it to work. Can you add the following property to `package.json` and we'll merge please? 

```
"jest": {
        "setupFilesAfterEnv": [
            "<rootDir>/src/setupTests.js"
        ]
    }
```

**Comment by luizcieslak** [comment]
done!

**Comment by daniel-norris** [comment]
Nice job, merged! 🎉🎉

**Pull request merged**
