### PR TITLE
Add simple child test for ListItem component

### LINKED ISSUE #99: Create a simple ListItem test
**Is your feature request related to a problem? Please describe.**
Test coverage across the application is low. We need to build confidence that the components have the expected behaviour that we want and to help mitigate any regression in the future.

**Describe the solution you'd like**
We need to implement better test coverage across the library. Ideally each component should be accompanied by a test case written using Jest. At a minimum the test should check whether the component successfully shows any child props. If you are able to include tests for any additional functionality then that would be appreciated!

We should have a test case covering the ListItem component implemented using Jest. More info on Jest can be found here.

For examples of how this is done, take a look at existing test cases in the library. An example would be the CardHeader or Input components.

You can run your tests using `npm run test` or to see test coverage across the library `npm run test:cov`.

This is part of epic #19.

### PR DESCRIPTION
**Pull request by lyonsbp**
Resolves #99

### CODE REVIEW

**Comment by daniel-norris** [comment]
Hey @lyonsbp - I've left you a comment on this in PR #103

**Comment by lyonsbp** [comment]
Coverage for this one should be at 100 now, can you confirm?

**Comment by lyonsbp** [comment]
Alright, this branch should also be at 100% now

**Review by daniel-norris — APPROVED** [review]
Nice work @lyonsbp. Sorry about the delay.

**Comment by daniel-norris** [comment]
Merged.

**Comment by lyonsbp** [comment]
Looks like Hacktoberfest isn't counting PRs merged today even if they were opened last week, what a bummer. I appreciate it anyway though, thanks!

**Pull request merged**
