### PR TITLE
Refactor toggle component

### LINKED ISSUE #5: Refactor the Toggle component
The existing toggle.js component needs to be refactored so that it uses the input[type=checkbox] element.

### PR DESCRIPTION
**Pull request by mankal111**
I've added a hidden input[type=checkbox] element in the component following [w3schools custom checkbox example](https://www.w3schools.com/howto/howto_css_custom_checkbox.asp) and I kept the custom one.
Both elements listen to the state and trigger the handleClick method. 

To test it I selected the hidden checkbox in devTools, in a variable called "nativeComponent", and after clicking the component I've printed the "checked" attribute:
custom to native
As you see clicking the component also changes the "checked" attribute of the hidden element.

On the other hand I've triggered a "click" event on the hidden element and the component responded too.
native to custom

I am not sure if this meets the criteria of #5. Let me know if it needs something more. 
Closes #5

### CODE REVIEW

**Comment by mankal111** [comment]
I've also added tests for the component, that check the existence of the native input element and its response on the component click.

**Review by daniel-norris — COMMENTED** [review]
Hey @mankal111, thanks for this contribution. I'm glad someone has finally taken the refactor issue that's been sitting there for so long! 

I like the approach you've taken but I'm left wondering if having a "hidden" element is really good for the user, especially from an accessibility perspective. 

One of the reasons I wanted to try refactoring it was to reduce the amount of markup being used. Also to see if we could provide the user with a solution that looked like the rest of the library but didn't require state management to control the colour of the toggle. 

W3Schools has an example actually that I think could work. It includes a label and input element which from an accessibility perspective is a lot better than what we currently have. Do you think you could refactor using that example while still keeping features like the toggle "light"? 

You could take it one step further and enable the user to pass a colour prop with a hex or rgb value to set any colour they want? 

https://www.w3schools.com/howto/howto_css_switch.asp

**Comment by mankal111** [comment]
Hey @daniel-norris, I've refactored the component following the W3Schools example. The checkbox is still hidden (you can check the '.switch input' selector in the css of the example you referenced) but since it is wrapped in a label, clicking everywhere on label checks/unchecks the checkbox. Then using the ':checked' I style the 'on' switch and indicator.

I have also removed state, converted the component to a functional one and added a 'indicatorColor' prop to enable the user to set it.

I just saw today that another contributor is working on the tests of the component (#80), so I removed mine.
We can create one more test for the 'indicatorColor' prop later.

**Comment by daniel-norris** [comment]
Thanks @mankal111, I'll take a look this evening.

**Review by daniel-norris — APPROVED** [review]
Nicely done @mankal111, thank you. This looks a lot better.

**Comment by daniel-norris** [comment]
Merged!

**Pull request merged**
