### PR TITLE
Add simple child test for ListGroup component

### LINKED ISSUE #98: Create a simple ListGroup test
**Is your feature request related to a problem? Please describe.**
Test coverage across the application is low. We need to build confidence that the components have the expected behaviour that we want and to help mitigate any regression in the future.

**Describe the solution you'd like**
We need to implement better test coverage across the library. Ideally each component should be accompanied by a test case written using Jest. At a minimum the test should check whether the component successfully shows any child props. If you are able to include tests for any additional functionality then that would be appreciated!

We should have a test case covering the ListGroup component implemented using Jest. More info on Jest can be found here.

For examples of how this is done, take a look at existing test cases in the library. An example would be the CardHeader or Input components.

You can run your tests using `npm run test` or to see test coverage across the library `npm run test:cov`.

This is part of epic #19.

### PR DESCRIPTION
**Pull request by lyonsbp**
Resolves #98

### CODE REVIEW

**Review by daniel-norris — CHANGES_REQUESTED** [review]
Hey @lyonsbp thanks for offering to contribute. This is a good first pass but there's a few things we need to improve before merging. I've had a look at this PR and #102 and both are under what we're trying to aim for in terms of test coverage >= 90%. 

ListGroup scored at 50% and ListItem a little less I think. 

image

Would you mind taking another look and seeing if you can improve? You can check test coverage by running `npm run test:cov` in each branch.

**Comment by lyonsbp** [comment]
Sure, Ill get the coverage up

**Comment by lyonsbp** [comment]
This one should be at full coverage now

**Comment by daniel-norris** [comment]
Nice job, merged!

**Pull request merged**
